[[ISSUERS]]
address = "rUaPXmyxjzPM3MvRWaxcnstHzfE734o4VN"
name = "XNUT"

[[TOKENS]]
issuer = "rUaPXmyxjzPM3MvRWaxcnstHzfE734o4VN"
currency = "XNUT"
name = "XNUT"
desc = "PNUT on Xrpl"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
